// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCheckbox: typeof import('element-plus/lib')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/lib')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElDatePicker: typeof import('element-plus/lib')['ElDatePicker']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElFormItem: typeof import('element-plus/lib')['ElFormItem']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElOption: typeof import('element-plus/lib')['ElOption']
    ElRadio: typeof import('element-plus/lib')['ElRadio']
    ElRadioGroup: typeof import('element-plus/lib')['ElRadioGroup']
    ElSelect: typeof import('element-plus/lib')['ElSelect']
    ElSwitch: typeof import('element-plus/lib')['ElSwitch']
    ElTimePicker: typeof import('element-plus/lib')['ElTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VForm: typeof import('vuetify/components')['VForm']
    VRow: typeof import('vuetify/components')['VRow']
    VTextField: typeof import('vuetify/components')['VTextField']
  }
}
